# The engine yaml api version
apiVersion: "3.0.0"

# The identifier for this repository
repository: mnist/mnist-torch

# The command to run
command: python vision/mnist/pytorch/pytorch_mnist.py --data-dir ./data/mnist
