# The engine yaml api version
apiVersion: 3.0.0

# The identifier for this repository
repository: mikyoking/mnist

# The command to run
command: python vision/mnist/tf/tensorflow_mnist.py --data-dir ./data/mnist
