# The engine yaml api version
apiVersion: "3.0.0"

# The identifier for this repository
repository: mnist/mnist-keras

# The command to run
command: python keras/mnist/keras_mnist.py --data-dir ./data/mnist
