# The engine yaml api version
apiVersion: 3.0.0

# The identifier for this repository
repository: wikitext/modeling

environment:
  CUDA_VISIBLE_DEVICES: "0,1"

# The command to run
command: python language/modeling/pytorch/train.py
  --model_type=roberta
  --model_name_or_path=roberta-base
  --per_gpu_train_batch_size 2
  --do_train
  --train_data_file=language/modeling/data/wikitext-2-raw/wiki.train.raw
  --do_eval
  --eval_data_file=language/modeling/data/wikitext-2-raw/wiki.train.raw
  --mlm
