# The engine yaml api version
apiVersion: "3.0.0"

# The identifier for this repository
repository: mnist/mnist-torch

# The command to run
command: python pytorch/mnist/pytorch_mnist.py --data-dir ./data/mnist

