# The engine yaml api version
apiVersion: 3.0.0

# The identifier for this repository
repository: squad/squad-pytorch

environment:
  CUDA_VISIBLE_DEVICES: '0'

# The command to run
command: python language/squad/pytorch/train.py
  --model_type bert
  --model_name_or_path bert-base-uncased
  --do_train
  --do_eval
  --train_file language/squad/data/train-v1.1.json
  --predict_file language/squad/data/dev-v1.1.json
  --per_gpu_train_batch_size 12
  --learning_rate 3e-5
  --num_train_epochs 2.0
  --max_seq_length 384
  --doc_stride 128
